#!/usr/bin/env bash

set -e

pvp="$1"
semantic="$2"

if [ -z "$pvp" ] || [ -z "$semantic" ]; then
    echo "Usage: bump-version <VERSION> <DEPENDENCY>"
    exit 1
fi

specs=(
 gogol/gogol.cabal
 core/gogol-core.cabal
 gen/gogol-gen.cabal
)

echo "Bumping version to $pvp and dependencies to == $semantic ..."

for cabal in ${specs[@]}; do
    sed -i"" "s/^\(version: *\).*$/\1$pvp/" $cabal
    sed -i"" "s/^\(.*gogol-[a-z0-9]* *== *\)\([0-9\.]\+\*\)$/\1$semantic.*/" $cabal
    sed -i"" "s/^\(.*gogol *== *\)\([0-9\.]\+\*\)$/\1$semantic.*/" $cabal
done

echo "Done."
