resolver: lts-22.43
compiler: ghc-9.6.6

notify-if-nix-on-path: false

extra-deps:
  - ede-0.3.4.0
  - aeson-2.2.3.0
  - attoparsec-aeson-2.2.2.0
  - character-ps-0.1
  - hashable-1.4.6.0
  - hindent-6.2.1

packages:
  - .
