resolver: lts-17.12

nix:
  enable: false
  packages: [zlib, icu67]
  add-gc-roots: true

flags: {}

extra-deps:
  - text-regex-replace-0.1.1.4
  - ede-0.3.2.0
  - prettyprinter-1.7.0 # for ede-0.3.2.0
  - hindent-5.3.2

packages:
  - "."