compiler: ghc-8.0.2
resolver: lts-8.18

flags: {}

extra-deps:
  - text-regex-replace-0.1.1.1
  - haskell-src-exts-1.17.1
  - hindent-4.6.4

packages:
  - '.'

nix:
  enable: true
  packages: [zlib, icu]
