#!/bin/sh -eux

set -euo pipefail

if [ $# -ne 2 ]; then
  echo "Usage: bump-version <VERSION> <DEPENDENCY>"
  exit 1
fi

pvp="$1"
semantic="$2"

specs=(
  examples/examples.cabal
  lib/gogol/gogol.cabal
  lib/gogol-core/gogol-core.cabal
)

echo "Bumping version to $pvp and dependencies to == $semantic ..."

for cabal in "${specs[@]}"; do
  sed -e "s/^\(version: *\).*$/\1$pvp/;" \
    -e "s/^\(.*gogol-[a-z0-9]* *== *\)\([0-9\.]\+\*\)$/\1$semantic.*/" \
    -e "s/^\(.*gogol *== *\)\([0-9\.]\+\*\)$/\1$semantic.*/" "$cabal" >"$cabal.new"

  mv "$cabal.new" "$cabal"
done

echo "Done."
